# Generated by Django 5.0 on 2025-10-15 00:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tripadvisor.validators.verifica_nascimento
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5, 'O nome deve conter no minimo 5 caracteres')])),
                ('nota', models.FloatField()),
                ('ingresso', models.BooleanField()),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('informacoes', models.TextField(blank=True, null=True)),
                ('site', models.URLField()),
                ('telefone', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.MinLengthValidator(11, 'Telefone deve ter 11 digitos.')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('classificacao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], default='Geral', max_length=8)),
                ('descricao', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('complemento', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('bairro', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cidade', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(10)])),
                ('passaporte', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10)])),
                ('senha', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)])),
                ('data_nascimento', models.DateField(validators=[tripadvisor.validators.verifica_nascimento.verifica_maior_idade])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('genero', models.CharField(choices=[('Homem', 'Man'), ('Mulher', 'Woman'), ('Não Binário', 'Non Binary'), ('Não Informado', 'Not Informed')], default='Não Informado', max_length=13)),
                ('pagina_pessoal', models.URLField(blank=True, max_length=150, null=True, validators=[django.core.validators.MinLengthValidator(15)])),
                ('biografia', models.TextField(blank=True, null=True)),
                ('lingua', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.MinLengthValidator(5)])),
                ('premium', models.BooleanField(default=False)),
                ('membro_desde', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripadvisor.atracao')),
                ('turno', models.CharField(choices=[('Manhã', 'Morning'), ('Tarde', 'Afternoon'), ('Noite', 'Night'), ('Madrugada', 'Early Morning')], default='Manhã', max_length=14)),
                ('duracao', models.TimeField()),
                ('guia', models.BooleanField()),
                ('participantes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('dificuldade', models.CharField(choices=[('Fácil', 'Easy'), ('Média', 'Medium'), ('Difícil', 'Hard'), ('Muito Difícil', 'Ultra Hard')], default='Fácil', max_length=13)),
            ],
            options={
                'abstract': False,
            },
            bases=('tripadvisor.atracao',),
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('atracao_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tripadvisor.atracao')),
                ('horario_abertura', models.DateTimeField()),
                ('horario_fechamento', models.DateTimeField()),
                ('acessibilidade', models.BooleanField()),
                ('classificao', models.CharField(choices=[('Geral', 'General'), ('Famílias', 'Families'), ('Casais', 'Couples'), ('Solo', 'Solo'), ('Negócios', 'Business'), ('Adulto', 'Adult')], default='Geral', max_length=13)),
            ],
            options={
                'abstract': False,
            },
            bases=('tripadvisor.atracao',),
        ),
        migrations.AddField(
            model_name='atracao',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='tripadvisor.categoria'),
        ),
        migrations.AddField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripadvisor.endereco'),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('nota', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('data_visita', models.DateField()),
                ('data_avaliacao', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('atracao', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tripadvisor.atracao')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tripadvisor.perfil')),
            ],
            options={
                'unique_together': {('perfil', 'atracao')},
            },
        ),
        migrations.AddField(
            model_name='atracao',
            name='avaliacoes',
            field=models.ManyToManyField(through='tripadvisor.Avaliacao', to='tripadvisor.perfil'),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('status', models.CharField(choices=[('Não Respondida', 'Not Answered'), ('Respondida', 'Answered'), ('Arquivada', 'Archived'), ('Fechada', 'Closed'), ('Moderada', 'Moderated'), ('Sinalizada', 'Flagged')], default='Não Respondida', max_length=14)),
                ('data', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('texto', models.TextField(validators=[django.core.validators.MinLengthValidator(50)])),
                ('data', models.DateField(auto_now_add=True)),
                ('likes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.perfil')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.questao')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Viagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descricao', models.TextField(blank=True, null=True)),
                ('destino', models.TextField(blank=True, max_length=100, null=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('pais_destino', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('inicio', models.DateField(default=django.utils.timezone.now)),
                ('final', models.DateField(default=django.utils.timezone.now)),
                ('orcamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('proposito', models.CharField(choices=[('Negócios', 'Business'), ('Férias', 'Vacation'), ('Mochilão', 'Backpacking'), ('Academico', 'Academic'), ('Outro', 'Outro')], default='Outro', max_length=9)),
                ('notas', models.TextField(blank=True, null=True)),
                ('transporte', models.CharField(choices=[('Trem', 'Train'), ('Avião', 'Plane'), ('Carro', 'Car'), ('Ônibus', 'Bus'), ('Diversos', 'Several')], default='Diversos', max_length=8)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.perfil')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='atracao',
            name='viagens',
            field=models.ManyToManyField(blank=True, to='tripadvisor.viagem'),
        ),
    ]
