# Generated by Django 5.0 on 2025-10-01 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='classifiacacao',
            new_name='classificacao',
        ),
    ]
