# Generated by Django 5.0 on 2025-11-12 22:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='avaliacoes',
            field=models.ManyToManyField(blank=True, through='tripadvisor.Avaliacao', to='tripadvisor.perfil'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tripadvisor.endereco'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='final',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do fim da viagem'),
        ),
        migrations.AlterField(
            model_name='viagem',
            name='inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do inicio da viagem'),
        ),
    ]
