# Generated by Django 5.0 on 2025-10-01 04:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0002_rename_classifiacacao_categoria_classificacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('numero', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('complemento', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)])),
                ('bairro', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('cidade', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)])),
                ('estado', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(5)])),
                ('pais', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('atracao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.atracao')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
