# Generated by Django 5.0 on 2025-12-04 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripadvisor', '0002_alter_atracao_avaliacoes_alter_atracao_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='atracao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.atracao'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tripadvisor.perfil'),
        ),
    ]
